env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
gomod:
  proxy: false


builds:
- main: ./cmd/drl-exporter/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - "7"
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{ .Version }} -X main.commitSha={{.Commit}} -X main.buildDate={{ .Date }}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch', 'go mod tidy']

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'


nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    maintainer: 'Abdul Khaliq <a.khaliq@outlook.my>'
    description: Dockerhub rate limit exporter.
    license: MIT
    formats:
    - deb
    - rpm
    dependencies:
    - git


dockers:
- image_templates:
  - 'khaliq/drl-exporter:{{ .Tag }}-amd64'
  - 'ghcr.io/kha7iq/drl-exporter:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
- image_templates:
  - 'khaliq/drl-exporter:{{ .Tag }}-arm64'
  - 'ghcr.io/kha7iq/drl-exporter:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64/v8"
  goarch: arm64

docker_manifests:
- name_template: 'khaliq/drl-exporter:{{ .Tag }}'
  image_templates:
  - 'khaliq/drl-exporter:{{ .Tag }}-amd64'
  - 'khaliq/drl-exporter:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/kha7iq/drl-exporter:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/kha7iq/drl-exporter:{{ .Tag }}-amd64'
  - 'ghcr.io/kha7iq/drl-exporter:{{ .Tag }}-arm64'
- name_template: 'khaliq/drl-exporter:latest'
  image_templates:
  - 'khaliq/drl-exporter:{{ .Tag }}-amd64'
  - 'khaliq/drl-exporter:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/kha7iq/drl-exporter:latest'
  image_templates:
  - 'ghcr.io/kha7iq/drl-exporter:{{ .Tag }}-amd64'
  - 'ghcr.io/kha7iq/drl-exporter:{{ .Tag }}-arm64'
