apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drl-exporter.fullname" . }}
  labels:
    {{- include "drl-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "drl-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "drl-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drl-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ default 2121 .Values.config.exporterPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DOCKERHUB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "drl-exporter.fullname" . }}-configmap
                  key: dockerhub-username
            - name: DOCKERHUB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "drl-exporter.fullname" . }}-secret
                  key: dockerhub-password
            - name: ENABLE_USER_AUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "drl-exporter.fullname" . }}-configmap
                  key: enable-user-auth
            - name: EXPORTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "drl-exporter.fullname" . }}-configmap
                  key: exporter-port
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
