apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
- name: Prometheus
  type: prom
  access: proxy
  orgId: 1
  url: http://prom:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
