global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prom'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'docker-hub-limit'
    static_configs:
    - targets: ['docker-hub-limit-exporter:8881']
